// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFCcC_Q1JKRb_0b6_Ph9vY8nrmoMerI74',
    appId: '1:283069957521:web:baca975c333098b94dc630',
    messagingSenderId: '283069957521',
    projectId: 'goal-mate-20289',
    authDomain: 'goal-mate-20289.firebaseapp.com',
    storageBucket: 'goal-mate-20289.firebasestorage.app',
    measurementId: 'G-PGWSTDY7SQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGG0JS9rSucTvgBI33-zy3cgKrBAIb4O0',
    appId: '1:283069957521:android:7b473b9e983945b44dc630',
    messagingSenderId: '283069957521',
    projectId: 'goal-mate-20289',
    storageBucket: 'goal-mate-20289.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHEv4pTFPqdREcL9J0bk4YC3SGFsMGa00',
    appId: '1:283069957521:ios:7c6900cfce295ca24dc630',
    messagingSenderId: '283069957521',
    projectId: 'goal-mate-20289',
    storageBucket: 'goal-mate-20289.firebasestorage.app',
    iosBundleId: 'com.example.goalMate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHEv4pTFPqdREcL9J0bk4YC3SGFsMGa00',
    appId: '1:283069957521:ios:7c6900cfce295ca24dc630',
    messagingSenderId: '283069957521',
    projectId: 'goal-mate-20289',
    storageBucket: 'goal-mate-20289.firebasestorage.app',
    iosBundleId: 'com.example.goalMate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFCcC_Q1JKRb_0b6_Ph9vY8nrmoMerI74',
    appId: '1:283069957521:web:3ff2ff9c7dce5a2c4dc630',
    messagingSenderId: '283069957521',
    projectId: 'goal-mate-20289',
    authDomain: 'goal-mate-20289.firebaseapp.com',
    storageBucket: 'goal-mate-20289.firebasestorage.app',
    measurementId: 'G-C9LGCRB7YV',
  );
}
