// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTbfmjLrwWqhHfSzo7zwr6EOLEDZdUtzw',
    appId: '1:264636968531:web:9213311cf199fb34aee0a6',
    messagingSenderId: '264636968531',
    projectId: 'goal-mate-9360f',
    authDomain: 'goal-mate-9360f.firebaseapp.com',
    storageBucket: 'goal-mate-9360f.firebasestorage.app',
    measurementId: 'G-YN8WQV1GQM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtuzLEoxC0NFfjZ6Oka9ggEyPdCfNWNB0',
    appId: '1:264636968531:android:5be2241190dce4e5aee0a6',
    messagingSenderId: '264636968531',
    projectId: 'goal-mate-9360f',
    storageBucket: 'goal-mate-9360f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD67rnzk7zFWbYHIgTZySqsFcEWNH_Zii0',
    appId: '1:264636968531:ios:824917d2bbdd4a94aee0a6',
    messagingSenderId: '264636968531',
    projectId: 'goal-mate-9360f',
    storageBucket: 'goal-mate-9360f.firebasestorage.app',
    iosBundleId: 'com.example.goalMate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD67rnzk7zFWbYHIgTZySqsFcEWNH_Zii0',
    appId: '1:264636968531:ios:824917d2bbdd4a94aee0a6',
    messagingSenderId: '264636968531',
    projectId: 'goal-mate-9360f',
    storageBucket: 'goal-mate-9360f.firebasestorage.app',
    iosBundleId: 'com.example.goalMate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTbfmjLrwWqhHfSzo7zwr6EOLEDZdUtzw',
    appId: '1:264636968531:web:d1e2689d1a250af7aee0a6',
    messagingSenderId: '264636968531',
    projectId: 'goal-mate-9360f',
    authDomain: 'goal-mate-9360f.firebaseapp.com',
    storageBucket: 'goal-mate-9360f.firebasestorage.app',
    measurementId: 'G-HQ96KE5WWG',
  );
}
